#!/bin/sh

#
# Copyright 2015-2016 Preetam J. D'Souza
# Copyright 2016 The Maru OS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Maru Linux initialization.
#
# This may be run before the entire system is up and running,
# (e.g. cross-bootstrap image build) so don't rely on any commands
# like systemctl.
#
# This needs to be idempotent.
#
# Creating a user that already exists returns failure so we use
# "id" to check if the user exists first.
#
# We ignore group creation failures ("|| true") since the subsequent
# adduser <user> <group> will fail if the group does not exist.
#

set -e
set -u

USER="lindroid"

# create default user account
if ! id -u "$USER" ; then
    adduser --disabled-password --gecos "" "$USER"
    # default password is username
    echo "${USER}:${USER}" | chpasswd
fi

# sudo rights
adduser "$USER" sudo

# internet access
addgroup --gid 3003 inet || true
adduser "$USER" inet

# raw sockets (ping)
addgroup --gid 3004 inet_raw || true
adduser "$USER" inet_raw

# sdcard r/w permissions
addgroup --gid 1015 sdcard_rw || true
adduser "$USER" sdcard_rw

# read systemd logs via journalctl
adduser "$USER" systemd-journal

# allow to acess input devices
adduser "$USER" input
adduser "sddm" input

# make sure root is added to Android's paranoid networking groups
adduser root inet
adduser root inet_raw

# if this release uses the unprivileged user _apt, grant it internet access
# note: we have to change the *primary* group because the default primary group
# 'nogroup' seems to prevent internet access even if _apt is added to inet as a
# secondary group
if id -u '_apt' >/dev/null ; then
    echo "Granting internet access to APT user..."
    usermod -g inet _apt
fi

## systemd ##

## udev ##

# remove any persistent interface naming rules
# This can be created when building Maru Desktop before
# our override kicks in.
PERSISTENT_NET_RULES="/etc/udev/rules.d/70-persistent-net.rules"
if [ -f "$PERSISTENT_NET_RULES" ] ; then
    rm "$PERSISTENT_NET_RULES"
fi

systemctl disable NetworkManager

#DEBHELPER#

exit 0
